---
- name: Check Juniper device configuration
  hosts: all
  gather_facts: no

  tasks:
  - name: Check correctness of commit configuration
    junos_command:
      commands: 
        - configure
        - commit check
        - commit
    register: result

  - name: Announce configuration status
    debug:
      msg: "{{ result.stdout[2] }}"
